package by.tc.task04.entity;

public enum RequestType {

    COUNT_SENTENCES_WITH_SAME_WORDS,
    INCREASING_WORD_COUNT,
    WORD_IN_FIRST_SENTENCE,
    SPECIFIED_LENGTH_WORDS,
    CHANGE_WORD_IN_SENTENCES,
    PRINT_IN_ALPHABETIC_ORDER,
    SORT_WORD_IN_ASCENDING_PROPORTION_OF_VOWELS,
    SORT_WORD_WITH_VOWELS_IN_ALPHABETIC_ORDER,
    SORT_WORD_WITH_SPECIFIED_CHARACTER,
    WORDS_IN_LIST,
    EXCLUDE_MAX_LENGTH_SUBSTRING,
    DELETE_ALL_WORDS_GIVEN_LENGTH,
    SORT_WORDS_IN_DESCENDING_ORDER_NUMBER_GIVEN_CHARACTER,
    FIND_MAX_PALINDROME,
    CONVERT_WORD,
    WORD_TO_SUBSTRING,

    GET_TEXT,
    DISCONNECT;
}
